[package]
name = "deps"
version = "0.1.0"
edition = "2021"

[dependencies]
libloading = "*"
plugins_core = { path = "../plugins/core" }
gtk = { package = "gtk4", version = "0.6.4", features = ["v4_10"] }
gdk4-win32 = "*"
windows = { version = "*", features = ["Win32_UI_HiDpi", "Win32_Foundation"] }
static_assertions = "*"
semver = "*"
ntapi = "*"
winapi = { version = "*", features = ["std"] }
fs2 = "*"
superslice = "*"

[lib]
path = "lib.rs"