[package]
name = "l4"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libloading = "0.7.4"
plugins_core = { path = "../plugins/core" }

[dependencies.gtk]
package = "gtk4"
version = "0.6.4"
features = ["v4_10", "blueprint"]

[dependencies.adw]
package = "libadwaita"
version = "0.3.1"

[build-dependencies]
glib-build-tools = "0.17.0"
walkdir = "2.3.3"
