[package]
name = "l4"
version = "0.1.0"
edition = "2021"

[package.metadata.winres]
OriginalFilename = "L4.exe"
ProductName = "L4"
FileDescription = "Launcher v4 or something"
LegalCopyright = "Copyright © 2023, Asriel Camora"
CompanyName = "WorkingRobot"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libloading = "0.7.4"
plugins_core = { path = "../plugins/core" }
gdk4-win32 = { version = "0.6.3", features = ["win32"] }
windows = { version = "0.47.0", features = ["Win32_UI_HiDpi", "Win32_Foundation"]}

[dependencies.gtk]
package = "gtk4"
version = "0.6.4"
features = ["v4_10", "blueprint"]

[dependencies.adw]
package = "libadwaita"
version = "0.3.1"

[build-dependencies]
embed-manifest = "1.3.1"
winres = "0.1.12"

[build-dependencies.build-scripts]
path = "build"